version: "3"
services:
  api:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/home/node/app
    ports:
      - "8080:8080"
    command: "npm start"
    networks:
      - web-checker

  frontend:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: "npm start"
    networks:
      - web-checker
networks:
  web-checker:
    driver: bridge